# Generated by Django 5.1.1 on 2024-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("gmp", models.CharField(max_length=100)),
                ("gain", models.IntegerField()),
                ("date", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("sauda", models.CharField(max_length=100)),
                ("allotment", models.CharField(max_length=100)),
                ("qty", models.CharField(max_length=100)),
                ("qi", models.CharField(max_length=100)),
                ("ri", models.CharField(max_length=100)),
                ("ni", models.CharField(max_length=100)),
                ("total_sub", models.CharField(max_length=100)),
            ],
        ),
    ]
