# Generated by Django 5.1.1 on 2024-09-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ipo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="companies", new_name="company",),
        migrations.RenameField(
            model_name="company", old_name="company", new_name="companies",
        ),
    ]
